server:
  port: 5050
  servlet:
    context-path: /api
    session:
      timeout: PT60M  # 过期时间 60M 一个小时

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${chat.db.host}:3306/chat?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${chat.db.pw}
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  mvc:
    throw-exception-if-no-handler-found: true  # 错误页处理
    path match:
      # 兼容swagger
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false
  redis:
    host: ${chat.redis.host}
    port: 6379
    password: ${chat.redis.pw}
    database: 0
    jedis:
      pool:
        max-active: 20  # 连接池最大连接数
        max-wait: -1  # 连接池最大阻塞等待时长，负值表示没有限制
        max-idle: 10  # 连接池中最大空闲连接
        min-idle: 0  # 连接池中最小空闲连接
    connect-timeout: 2000  # 连接超时时间


mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

ws:
  port: 5051  # websocket端口

project:
  folder: E:/E/Chat/Chat-Source/  # 服务器存在的磁盘

logging:
  level:
    root: debug

knife4j:
  enable: true
  openapi:
    title: 简易聊天软件文档
    description: "简易聊天软件文档"
    email: 1633433173@qq.com
    concat: happlay71
    url: https://happlay.online
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - online.happlay.chat.controller

admin:
  emails: 1633433173@qq.com